/**
 * Fetch Wintermute's master delegate-categorization table from Dune and write
 * it to content/wintermute-delegates.json.
 *
 * Wintermute maintains a hand-curated table of tagged EIP-7702 delegate
 * contracts as Dune query 5145294, with columns:
 *   - address (hex string)
 *   - name             (human-readable, e.g. "Bitget", "Metamask", "CrimeEnjoyor")
 *   - category         (e.g. "Retail Wallets", "Crime", "Service")
 *
 * We read this via Dune's "get latest results" API — which reads the query's
 * cached execution rather than triggering a new one (cheap, doesn't consume
 * execution credits).
 *
 * Usage:
 *   DUNE_API_KEY=xxx npx tsx scripts/fetch-wintermute-delegates.ts
 *   DUNE_API_KEY=xxx npx tsx scripts/fetch-wintermute-delegates.ts --inspect
 *
 * With --inspect, dumps the raw response and exits without writing (useful
 * when Wintermute changes the query schema and we need to see what's there).
 */

import { writeFile, readFile } from "node:fs/promises";
import { resolve } from "node:path";

const QUERY_ID = 5145294;
const OUTPUT_PATH = resolve(process.cwd(), "content/wintermute-delegates.json");
const DUNE_API = `https://api.dune.com/api/v1/query/${QUERY_ID}/results?limit=10000`;

type DuneRow = {
  address?: string;
  name?: string;
  category?: string;
  [k: string]: unknown;
};

type DuneResponse = {
  execution_id?: string;
  query_id?: number;
  state?: string;
  result?: { rows?: DuneRow[]; metadata?: { column_names?: string[] } };
  error?: string;
};

async function main() {
  const apiKey = process.env.DUNE_API_KEY;
  if (!apiKey) {
    console.error("DUNE_API_KEY is not set");
    process.exit(1);
  }

  const inspect = process.argv.includes("--inspect");

  console.log(`Fetching Dune query ${QUERY_ID}...`);
  const resp = await fetch(DUNE_API, {
    headers: { "X-Dune-API-Key": apiKey },
  });

  if (!resp.ok) {
    console.error(`Dune API error: ${resp.status} ${resp.statusText}`);
    console.error(await resp.text());
    process.exit(1);
  }

  const data = (await resp.json()) as DuneResponse;
  if (data.state && data.state !== "QUERY_STATE_COMPLETED") {
    console.error(`Query not in completed state: ${data.state}`);
    process.exit(1);
  }

  const rows = data.result?.rows ?? [];
  const columns = data.result?.metadata?.column_names ?? [];

  console.log(`Received ${rows.length} rows.`);
  console.log(`Columns: ${columns.join(", ")}`);

  if (inspect) {
    console.log("\nFirst 3 rows:");
    console.log(JSON.stringify(rows.slice(0, 3), null, 2));
    process.exit(0);
  }

  // Validate schema up front — fail loudly if Wintermute changed the query.
  const REQUIRED = ["address", "name", "category"];
  const missing = REQUIRED.filter((c) => !columns.includes(c));
  if (missing.length > 0) {
    console.error(
      `Query ${QUERY_ID} is missing expected columns: ${missing.join(", ")}. ` +
        `Actual columns: ${columns.join(", ")}. ` +
        "Aborting to avoid publishing corrupt data.",
    );
    process.exit(1);
  }

  // Transform + dedupe by address (query rows are one-per-contract already, but
  // defense-in-depth — a single duplicate row would silently overwrite otherwise).
  const seen = new Set<string>();
  const entries: Array<{
    address: string;
    name: string;
    category: string;
  }> = [];

  for (const row of rows) {
    const addr = normalizeAddress(row.address);
    if (!addr) continue;
    if (seen.has(addr)) continue;
    if (!row.name || !row.category) continue;

    seen.add(addr);
    entries.push({
      address: addr,
      name: String(row.name).trim(),
      category: String(row.category).trim(),
    });
  }

  // Sort by category then name — makes commit diffs readable when the data changes.
  entries.sort((a, b) => {
    const c = a.category.localeCompare(b.category);
    return c !== 0 ? c : a.name.localeCompare(b.name);
  });

  console.log(`Validated ${entries.length} unique delegates.`);
  const categoryCounts = entries.reduce<Record<string, number>>((acc, e) => {
    acc[e.category] = (acc[e.category] ?? 0) + 1;
    return acc;
  }, {});
  console.log("By category:", categoryCounts);

  // Read existing file to preserve any custom meta fields, then overwrite.
  let existing: { meta: Record<string, unknown> } | null = null;
  try {
    existing = JSON.parse(await readFile(OUTPUT_PATH, "utf8"));
  } catch {
    // fine — first run
  }

  const payload = {
    meta: {
      ...(existing?.meta ?? {}),
      source: "Wintermute Research",
      sourceUrl: "https://dune.com/wintermute_research/eip7702",
      queryId: QUERY_ID,
      syncedAt: new Date().toISOString(),
      description:
        "Auto-generated by scripts/fetch-wintermute-delegates.ts on a nightly schedule. Do NOT edit by hand — edits will be overwritten. To add manually-curated entries, use content/manual-delegates.json instead.",
    },
    entries,
  };

  await writeFile(OUTPUT_PATH, JSON.stringify(payload, null, 2) + "\n");
  console.log(`Wrote ${OUTPUT_PATH}`);
}

function normalizeAddress(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim().toLowerCase();
  if (!/^0x[0-9a-f]{40}$/.test(trimmed)) return null;
  return trimmed;
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
